// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// [START messages]
type MsgType int32

const (
	MsgType_Login    MsgType = 0
	MsgType_LoginRes MsgType = 1
)

var MsgType_name = map[int32]string{
	0: "Login",
	1: "LoginRes",
}

var MsgType_value = map[string]int32{
	"Login":    0,
	"LoginRes": 1,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Msg struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=type,proto3,enum=message.MsgType" json:"type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_Login
}

func (m *Msg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UserPwd              string   `protobuf:"bytes,4,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Coin                 int32    `protobuf:"varint,6,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

func (m *User) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

type MsgLogin struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLogin) Reset()         { *m = MsgLogin{} }
func (m *MsgLogin) String() string { return proto.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()    {}
func (*MsgLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MsgLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLogin.Unmarshal(m, b)
}
func (m *MsgLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLogin.Marshal(b, m, deterministic)
}
func (m *MsgLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLogin.Merge(m, src)
}
func (m *MsgLogin) XXX_Size() int {
	return xxx_messageInfo_MsgLogin.Size(m)
}
func (m *MsgLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLogin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLogin proto.InternalMessageInfo

func (m *MsgLogin) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type MsgSignIn struct {
	ContinuousSignInTimes int32    `protobuf:"varint,1,opt,name=continuousSignInTimes,proto3" json:"continuousSignInTimes,omitempty"`
	BonusCoin             int32    `protobuf:"varint,2,opt,name=bonusCoin,proto3" json:"bonusCoin,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MsgSignIn) Reset()         { *m = MsgSignIn{} }
func (m *MsgSignIn) String() string { return proto.CompactTextString(m) }
func (*MsgSignIn) ProtoMessage()    {}
func (*MsgSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MsgSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignIn.Unmarshal(m, b)
}
func (m *MsgSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignIn.Marshal(b, m, deterministic)
}
func (m *MsgSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignIn.Merge(m, src)
}
func (m *MsgSignIn) XXX_Size() int {
	return xxx_messageInfo_MsgSignIn.Size(m)
}
func (m *MsgSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignIn proto.InternalMessageInfo

func (m *MsgSignIn) GetContinuousSignInTimes() int32 {
	if m != nil {
		return m.ContinuousSignInTimes
	}
	return 0
}

func (m *MsgSignIn) GetBonusCoin() int32 {
	if m != nil {
		return m.BonusCoin
	}
	return 0
}

type MsgLoginRes struct {
	User                 *User      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SignInfo             *MsgSignIn `protobuf:"bytes,2,opt,name=signInfo,proto3" json:"signInfo,omitempty"`
	Code                 int32      `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Error                string     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgLoginRes) Reset()         { *m = MsgLoginRes{} }
func (m *MsgLoginRes) String() string { return proto.CompactTextString(m) }
func (*MsgLoginRes) ProtoMessage()    {}
func (*MsgLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MsgLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLoginRes.Unmarshal(m, b)
}
func (m *MsgLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLoginRes.Marshal(b, m, deterministic)
}
func (m *MsgLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLoginRes.Merge(m, src)
}
func (m *MsgLoginRes) XXX_Size() int {
	return xxx_messageInfo_MsgLoginRes.Size(m)
}
func (m *MsgLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLoginRes proto.InternalMessageInfo

func (m *MsgLoginRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MsgLoginRes) GetSignInfo() *MsgSignIn {
	if m != nil {
		return m.SignInfo
	}
	return nil
}

func (m *MsgLoginRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgLoginRes) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Msg)(nil), "message.Msg")
	proto.RegisterType((*User)(nil), "message.User")
	proto.RegisterType((*MsgLogin)(nil), "message.MsgLogin")
	proto.RegisterType((*MsgSignIn)(nil), "message.MsgSignIn")
	proto.RegisterType((*MsgLoginRes)(nil), "message.MsgLoginRes")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x9b, 0xb4, 0xc9, 0xb4, 0x95, 0x32, 0xa8, 0x04, 0xf1, 0x50, 0x83, 0x87, 0x22,
	0xd8, 0x43, 0xf5, 0x0d, 0xd4, 0x43, 0xc1, 0x80, 0xc4, 0x7a, 0x96, 0x36, 0x5d, 0xc3, 0xa2, 0xd9,
	0x2d, 0x3b, 0x09, 0xd2, 0x57, 0xf0, 0xec, 0x03, 0xcb, 0xce, 0x26, 0xd5, 0x83, 0x07, 0x6f, 0xf9,
	0x66, 0x66, 0x67, 0xfe, 0xf9, 0x27, 0x30, 0x2a, 0x05, 0xd1, 0xaa, 0x10, 0xb3, 0xad, 0xd1, 0x95,
	0xc6, 0x7e, 0x83, 0xc9, 0x3d, 0x74, 0x53, 0x2a, 0xf0, 0x02, 0xfc, 0x6a, 0xb7, 0x15, 0xb1, 0x37,
	0xf1, 0xa6, 0x87, 0xf3, 0xf1, 0xac, 0xad, 0x4e, 0xa9, 0x58, 0xee, 0xb6, 0x22, 0xe3, 0x2c, 0xc6,
	0xd0, 0xcf, 0xb5, 0xaa, 0x84, 0xaa, 0xe2, 0xce, 0xc4, 0x9b, 0x0e, 0xb3, 0x16, 0x93, 0x2f, 0x0f,
	0xfc, 0x67, 0x12, 0x06, 0x4f, 0xa0, 0x57, 0x93, 0x30, 0x8b, 0x3b, 0x6e, 0x15, 0x64, 0x0d, 0xe1,
	0x29, 0x84, 0x4a, 0xe6, 0x6f, 0x6a, 0x55, 0x0a, 0x7e, 0x1b, 0x65, 0x7b, 0xc6, 0x23, 0x08, 0x44,
	0xb9, 0x92, 0xef, 0x71, 0x97, 0x13, 0x0e, 0xec, 0x30, 0xfb, 0xf6, 0xf1, 0x63, 0x13, 0xfb, 0x1c,
	0x6f, 0xd1, 0xd6, 0x53, 0xae, 0x8d, 0x88, 0x03, 0x1e, 0xe1, 0x00, 0x11, 0xfc, 0x5c, 0x4b, 0x15,
	0xf7, 0x38, 0xc8, 0xdf, 0xc9, 0x15, 0x84, 0x29, 0x15, 0x0f, 0xba, 0x90, 0x0a, 0xcf, 0xc1, 0xb7,
	0x0d, 0x58, 0xd7, 0x60, 0x3e, 0xda, 0xaf, 0x68, 0x65, 0x67, 0x9c, 0x4a, 0x5e, 0x20, 0x4a, 0xa9,
	0x78, 0x92, 0x85, 0x5a, 0x28, 0xbc, 0x81, 0x63, 0xbb, 0x9d, 0x54, 0xb5, 0xae, 0xc9, 0xc5, 0x96,
	0xb2, 0x14, 0xd4, 0x2c, 0xf6, 0x77, 0x12, 0xcf, 0x20, 0x5a, 0x6b, 0x55, 0xd3, 0xad, 0x95, 0xd2,
	0xe1, 0xca, 0x9f, 0x40, 0xf2, 0xe9, 0xc1, 0xa0, 0x15, 0x94, 0x09, 0xfa, 0x87, 0x26, 0x9c, 0x41,
	0x48, 0xdc, 0xff, 0x55, 0x73, 0xbf, 0xc1, 0x1c, 0x7f, 0x5f, 0xc7, 0xcd, 0xce, 0xf6, 0x35, 0xce,
	0x86, 0x8d, 0x60, 0x2f, 0xd9, 0x86, 0x8d, 0x33, 0xd8, 0x18, 0x6d, 0x1a, 0x23, 0x1d, 0x5c, 0x26,
	0xd0, 0x6f, 0xce, 0x8b, 0x11, 0x04, 0xac, 0x69, 0x7c, 0x80, 0x43, 0x08, 0x5b, 0x79, 0x63, 0x6f,
	0xdd, 0xe3, 0xdf, 0xe5, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xac, 0x0e, 0x0a, 0x3f, 0x02,
	0x00, 0x00,
}
